# coding: iso-8859-1

"""Constants for parsing the gender.c name database: list of countries and Unicode mapping."""

# The countries in order, see data/gender.c/nam_dict.txt for details.  We'll ignore the non-ISO
# countries other than Arabia/Persia.  We'll also eventually break up combinations of countries
# like India/Sri Lanka and Kazakhstan etc.
COUNTRIES = [
    ('gb', 'United Kingdom'),
    ('ie', 'Ireland'),
    ('us', 'United States'),
    ('it', 'Italy'),
    ('mt', 'Malta'),
    ('pt', 'Portugal'),
    ('es', 'Spain'),
    ('fr', 'France'),
    ('be', 'Belgium'),
    ('lu', 'Luxembourg'),
    ('nl', 'Netherlands'),
    ('EF', 'East Frisia'),  # Not an ISO-2 country, ignored.
    ('de', 'Germany'),
    ('at', 'Austria'),
    ('ch', 'Switzerland'),
    ('is', 'Iceland'),
    ('dk', 'Denmark'),
    ('no', 'Norway'),
    ('se', 'Sweden'),
    ('fi', 'Finland'),
    ('ee', 'Estonia'),
    ('lv', 'Latvia'),
    ('lt', 'Lithuania'),
    ('pl', 'Poland'),
    ('cz', 'Czech Republic'),
    ('sk', 'Slovakia'),
    ('hu', 'Hungary'),
    ('ro', 'Romania'),
    ('bg', 'Bulgaria'),
    ('ba', 'Bosnia and Herzegovina'),
    ('hr', 'Croatia'),
    ('xk', 'Kosovo'),
    ('mk', 'Macedonia'),
    ('me', 'Montenegro'),
    ('rs', 'Serbia'),
    ('si', 'Slovenia'),
    ('al', 'Albania'),
    ('gr', 'Greece'),
    ('ru', 'Russian Federation'),
    ('by', 'Belarus'),
    ('md', 'Republic of Moldova'),
    ('ua', 'Ukraine'),
    ('am', 'Armenia'),
    ('az', 'Azerbaijan'),
    ('ge', 'Georgia'),
    ('kz/kg/tj/tm/uz', 'Kazakhstan, Kyrgyzstan, Tajikistan, Turkmenistan, Uzbekistan'),
    ('tr', 'Turkey'),
    ('AR', 'Arab countries'),  # Not an ISO-2 country.
    ('il', 'Israel'),
    ('cn', 'China'),
    ('in/lk', 'India, Sri Lanka'),
    ('jp', 'Japan'),
    ('kr', 'Repulic of Korea'),
    ('vn', 'Viet Nam'),
    ('XX', 'Other countries'),  # Ignored.
]

UNICODE_MAP = {
    256: ['<A/>'],
    257: ['<a/>'],
    258: ['<Â>'],
    259: ['<â>'],
    260: ['<A,>'],
    261: ['<a,>'],
    262: ['<C´>'],
    263: ['<c´>'],
    268: ['<C^>', '<CH>'],
    269: ['<c^>', '<ch>'],
    271: ['<d´>'],
    272: ['<Ð>', '<DJ>'],
    273: ['<ð>', '<dj>'],
    274: ['<E/>'],
    275: ['<e/>'],
    278: ['<E°>'],
    279: ['<e°>'],
    280: ['<E,>'],
    281: ['<e,>'],
    282: ['<Ê>'],
    283: ['<ê>'],
    286: ['<G^>'],
    287: ['<g^>'],
    290: ['<G,>'],
    291: ['<g´>'],
    298: ['<I/>'],
    299: ['<i/>'],
    304: ['<I°>'],
    305: ['<i>'],
    306: ['<IJ>'],
    307: ['<ij>'],
    310: ['<K,>'],
    311: ['<k,>'],
    315: ['<L,>'],
    316: ['<l,>'],
    317: ['<L´>'],
    318: ['<l´>'],
    321: ['<L/>'],
    322: ['<l/>'],
    325: ['<N,>'],
    326: ['<n,>'],
    327: ['<N^>'],
    328: ['<n^>'],
    336: ['<Ö>'],
    337: ['<ö>'],
    338: ['Œ', '<OE>'],
    339: ['œ', '<oe>'],
    344: ['<R^>'],
    345: ['<r^>'],
    350: ['<S,>'],
    351: ['<s,>'],
    352: ['Š', '<S^>', '<SCH>', '<SH>'],
    353: ['š', '<s^>', '<sch>', '<sh>'],
    354: ['<T,>'],
    355: ['<t,>'],
    357: ['<t´>'],
    362: ['<U/>'],
    363: ['<u/>'],
    366: ['<U°>'],
    367: ['<u°>'],
    370: ['<U,>'],
    371: ['<u,>'],
    379: ['<Z°>'],
    380: ['<z°>'],
    381: ['<Z^>'],
    382: ['<z^>'],
    7838: ['<ß>'],
}
